---
- name: Download the CirrOS image
  get_url:
    url: "{{ tripleo_overcloud_cirros_url }}"
    dest: /tmp/cirros.img

- name: Upload the CirrOS image
  os_image:
    name: cirros
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /tmp/cirros.img
    properties:
      cpu_arch: x86_64
      distro: ubuntu

- name: Clean up CirrOS image
  file:
    path: /tmp/cirros.img
    state: absent

- name: Create a public network
  os_network:
    name: public_network
    provider_network_type: flat
    provider_physical_network: datacentre
    external: True
    shared: True

- name: Create a subnet on the public network
  os_subnet:
    name: public_subnet
    network_name: public_network
    cidr: 10.0.0.0/24
    allocation_pool_start: 10.0.0.50
    allocation_pool_end: 10.0.0.254
    gateway_ip: 10.0.0.1
    dns_nameservers:
      - 1.1.1.1
      - 8.8.8.8

- name: Create a private network
  os_network:
    name: private_network

- name: Create a private subnet
  os_subnet:
    name: private_subnet
    network_name: private_network
    cidr: 192.168.100.0/24

- name: Create a public router
  os_router:
    name: public_router
    # Default gateway
    network: public_network
    # Private network
    interfaces:
      - private_subnet

- name: Create a security group
  os_security_group:
    name: ssh_and_icmp
    state: present

- name: Allow incoming ICMP (ping) traffic
  os_security_group_rule:
    security_group: ssh_and_icmp
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0

- name: Allow incoming SSH traffic
  os_security_group_rule:
    security_group: ssh_and_icmp
    protocol: tcp
    port_range_min: 22
    port_range_max: 22

- name: Allow all outgoing traffic
  os_security_group_rule:
    security_group: ssh_and_icmp
    direction: egress
    remote_ip_prefix: 0.0.0.0/0

- name: Create a tiny flavor for CirrOS
  os_nova_flavor:
    name: cirros_flavor
    vcpus: 1
    disk: 1
    ram: 64

- name: Create a CirrOS instance
  os_server:
    name: cirros_instance
    image: cirros
    flavor: cirros_flavor
    network: private_network
    security_groups:
      - ssh_and_icmp

- name: Create a floating IP address
  os_floating_ip:
    server: cirros_instance
    network: public_network
    nat_destination: private_network
    wait: True
    timeout: 180
  register: floating_ip

- debug:
    var: "{{ floating_ip }}"

