---
- name: Download an image
  get_url:
    url: "{{ tripleo_overcloud_image_url }}"
    dest: "/tmp/{{ tripleo_overcloud_image_name }}.img"

- name: Upload the image to Glance
  os_image:
    name: cirros
    container_format: bare
    disk_format: qcow2
    state: present
    filename: "/tmp/{{ tripleo_overcloud_image_name }}.img"
    properties:
      cpu_arch: x86_64

- name: Clean up the image from the local file system
  file:
    path: "/tmp/{{ tripleo_overcloud_image_name }}.img"
    state: absent

- name: Create a public network
  os_network:
    name: public_network
    provider_network_type: flat
    provider_physical_network: datacentre
    external: True
    shared: True

- name: Create a subnet on the public network
  os_subnet:
    name: public_subnet
    network_name: public_network
    cidr: "{{ tripleo_overcloud_public_cidr }}"
    allocation_pool_start: "{{ tripleo_overcloud_public_allocation_pool.start }}"
    allocation_pool_end: "{{ tripleo_overcloud_public_allocation_pool.end }}"
    gateway_ip: "{{ tripleo_overcloud_public_gateway_ip }}"
    dns_nameservers: "{{ tripleo_overcloud_public_dns_nameservers }}"

- name: Create a private network
  os_network:
    name: private_network

- name: Create a private subnet
  os_subnet:
    name: private_subnet
    network_name: private_network
    cidr: "{{ tripleo_overcloud_private_cidr }}"

- name: Create a public router
  os_router:
    name: public_router
    # Default gateway
    network: public_network
    # Private network
    interfaces:
      - private_subnet

- name: Create a security group
  os_security_group:
    name: ssh_and_icmp
    state: present

- name: Allow incoming ICMP (ping) traffic
  os_security_group_rule:
    security_group: ssh_and_icmp
    protocol: icmp
    remote_ip_prefix: 0.0.0.0/0

- name: Allow incoming SSH traffic
  os_security_group_rule:
    security_group: ssh_and_icmp
    protocol: tcp
    port_range_min: 22
    port_range_max: 22

- name: Create a custom flavor
  os_nova_flavor:
    name: "{{ tripleo_overcloud_flavor.name }}"
    vcpus: "{{ tripleo_overcloud_flavor.vcpus }}"
    disk: "{{ tripleo_overcloud_flavor.disk }}"
    ram: "{{ tripleo_overcloud_flavor.ram }}"

- name: Create an instance
  os_server:
    name: "{{ tripleo_overcloud_image_name }}_instance"
    image: "{{ tripleo_overcloud_image_name }}"
    flavor: "{{ tripleo_overcloud_flavor.name }}"
    network: private_network
    security_groups:
      - ssh_and_icmp

- name: Create a floating IP address
  os_floating_ip:
    server: "{{ tripleo_overcloud_image_name }}_instance"
    network: public_network
    nat_destination: private_network
    wait: True
    timeout: 180
  register: floating_ip

- debug:
    var: "{{ floating_ip }}"

